### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by lrk** [smunaut/blackmagic-misc#3]
Hi @smunaut,could you select/add a license to indicate how other peoples can / or not reuse your work.

Thank you.

**Comment by smunaut** [comment]
?

Each file has a license header.

This is a random collection of stuff I might add to in the future, I can't promise every file in here will have the same license, depends on what it is/will be so there is no "global" license. But each individual file has a copyright header and the associated SPDX license identifier.

**Comment by lrk** [comment]
Oh sorry, @smunaut I was expecting a LICENSE file, and did not see the headers in files. 

Thank you.
